INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:02:06] "[33mPOST /api/login HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:03:29] "[31m[1mPOST /login HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:03:46] "POST /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:04:46] "[31m[1mPOST /api/register HTTP/1.1[0m" 400 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:05:16] "[31m[1mPOST /api/register HTTP/1.1[0m" 400 -
ERROR:main:Exception on /api/register [POST]
Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 115, in register
    if len(db.execute("SELECT * FROM users WHERE email = ?", data["email"])):
                                                             ~~~~^^^^^^^^^
KeyError: 'email'
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:07:01] "[35m[1mPOST /api/register HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:08:05] "[31m[1mPOST /api/register HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:09:14] "POST /api/register HTTP/1.1" 200 -
ERROR:main:Exception on /api/register [POST]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: table teachers has no column named student_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 140, in register
    db.execute(f"INSERT INTO { table } (student_id, name, last_name, birth_date) VALUES (?, ?, ?, ?)",
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: table teachers has no column named student_id
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:10:10] "[35m[1mPOST /api/register HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:11:59] "[31m[1mPOST /api/register HTTP/1.1[0m" 422 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/register [POST]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: near "?": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 141, in register
    db.execute(f"INSERT INTO { table } (? , name, last_name, birth_date) VALUES (?, ?, ?, ?)", id_type, new_user_id, data["name"], data["last_name"], data["birth_date"])
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: near "?": syntax error
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:15:40] "[35m[1mPOST /api/register HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:17:02] "POST /api/register HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:18:19] "GET /api/schools HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:19:47] "[33mGET /api/schools/PataliAn HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:20:23] "[33mGET /api/schools/PataliAn HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:21:46] "[33mGET /api/schools/Patalian HTTP/1.1[0m" 404 -
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 190, in get_student
    personal_info = db.execute("SELECT * FROM students WHERE id = ?", user_info["id"])
                                                                      ~~~~~~~~~^^^^^^
TypeError: list indices must be integers or slices, not str
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:22:07] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 191, in get_student
    personal_info = db.execute("SELECT * FROM students WHERE id = ?", user_info["id"])
                                                                      ~~~~~~~~~^^^^^^
TypeError: list indices must be integers or slices, not str
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:23:00] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: no such column: id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 191, in get_student
    personal_info = db.execute("SELECT * FROM students WHERE id = ?", user_info["id"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: no such column: id
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:23:19] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: no such column: id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 191, in get_student
    personal_info = db.execute("SELECT * FROM students WHERE id = ?", user_info["id"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: no such column: id
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:23:56] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: no such column: id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 190, in get_student
    personal_info = db.execute("SELECT * FROM students WHERE id = ?", user_info)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: no such column: id
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:24:50] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 191, in get_student
    class_id = db.execute("SELECT * FROM student_to_class WHERE student_id = ?", user_info["id"])["class_id"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:25:43] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 191, in get_student
    class_id = db.execute("SELECT * FROM student_to_class WHERE student_id = ?", user_info["id"])[0]["class_id"]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:26:07] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /api/student/Patalian [GET]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.OperationalError: near "FROM": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 206, in get_student
    if not check_assignment_class(user_info["id"], STUDENT_ROLE):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 193, in check_assignment_class
    if not any(db.execute(f"SELECT FROM {table} WHERE {id_type} = ?", id_)):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 45, in execute
    raise RuntimeError(f"Error executing query: {e}")
RuntimeError: Error executing query: near "FROM": syntax error
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:31:51] "[35m[1mGET /api/student/Patalian HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 08:32:07] "GET /api/student/Patalian HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:41:52] "GET /api/student?s=Patalian HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:42:59] "[31m[1mPOST /api/classes HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:44:22] "[31m[1mPOST /api/classes HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:45:24] "[31m[1mPOST /api/classes HTTP/1.1[0m" 400 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:46:19] "POST /api/classes HTTP/1.1" 200 -
ERROR:main:Exception on /api/classes [POST]
Traceback (most recent call last):
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 29, in execute
    self.cur.execute(sql, args)
sqlite3.IntegrityError: UNIQUE constraint failed: classes.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\main.py", line 336, in create_class
    db.execute("INSERT INTO classes (id, student_count, class_room) VALUES (?, ?, ?)", data["classId"], data["studentCount"], data["classRoom"])
  File "C:\Users\potch\GitHubRepositories\TimeTable\src\sql.py", line 43, in execute
    raise ValueError("Value error occurred")
ValueError: Value error occurred
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:46:25] "[35m[1mPOST /api/classes HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:80
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/May/2024 10:48:44] "[31m[1mPOST /api/classes HTTP/1.1[0m" 400 -
